### ISSUE TITLE
Error when compiling gchp  14.4.3

### ISSUE THREAD

**Issue by mgarciavi** [geoschem/gchp#438]
### Your name

Marta García Vivanco

### Your affiliation

CIEMAT, Madrid, Spain

### What happened? What did you expect to happen?

I have tried to compile the recent 14.4.3 version, with gcc10-2-0 and ompi4-1-1. The compilation failed  (make –j) when building MAPL.history (error attached, at 81% of compilation) (it seems related to ESMF).
 
I’m attaching the current error (log-mgv.txt), in case could have any suggestion to address this error. I’m also attaching the CMakeCache.txt file. I hadn't seen this error in the previous version.

The libraries I have uploaded are:

Currently Loaded Modules:
  1) gcc-10.2.0-4ijy4tr                 4) netcdf-c-4.9.2-uuoit2h          7) hdf5-1.14.0-mi2lil6
  2) cmake-3.22.2-jt5gpvc               5) netcdf-fortran-4.5.3-57v5v4z    8) esmf-8.0.1-gcc-10.2.0-ou3tiq7
  3) openmpi-4.1.0-gcc-10.2.0-eeim4ka   6) flex-2.6.3-gcc-10.2.0-7a3pjij   

Thank you for your help.

### What are the steps to reproduce the bug?

After recovering the code with git commands, I created the build directory under GCHP and ran the cmake command (it seems successful, although with some missing libraries, such as python, that not seem to be essential). Then I did "make -j", and I found the error.
[CMakeCache.txt](https://github.com/user-attachments/files/16732314/CMakeCache.txt)
[log-make-mgv.txt](https://github.com/user-attachments/files/16732315/log-make-mgv.txt)

### What GCHP version were you using?

14.4.3 

### What environment were you running GCHP on?

Local cluster

### What compiler and version were you using?

gcc10.2.0

### What MPI library and version were you using?

openmpi 4.1.1

### Will you be addressing this bug yourself?

Yes

**Comment by mgarciavi** [comment]
Hi again,

I've tried with another compiler, gcc9.4.0 and  ompi4.1.1, and the compilation worked.

My previous problem was with gcc10.2.0, only to know if other people could compile with this gcc version, to see if this is a problem with our machines/libraries.


But with the gcc9.4.0  for the moment I have a problem when executing gchp, related to MAPL_Generic.F90 (see attached document). I will check more, but maybe you have some suggestions to fix this.

[slurm-489742.txt](https://github.com/user-attachments/files/16747590/slurm-489742.txt)

I'm using 48 cores, 1 node.

Thank you in advance! 
(maybe I can change the tittle of this issue to  "Error when compiling/executing gchp 14.4.3"... tell me if this is better..)

Best regards,

**Comment by yantosca** [comment]
Thanks @mgarciavi for the feedback.  Glad that it worked with gcc 9.4.0!

On our system we use:

- gcc 10.2.0
- openmp 4.1.0
- netcdf-c 4.8.0
- netcdf-fortran 4.5.3
- ESMF 8.4.2

The current GCHP version is using an older version of MAPL (v2.28 I believe).  This may not be compatible with the latest ESMF version (which I think is 8.6.0).  We are waiting for GMAO to release MAPL3, which will likely require a newer ESMF.  So if you can use ESMF 8.4.2 or earlier that should work with gcc 10.2.0.

**Comment by yantosca** [comment]
Also: I believe we have a container (Docker image) with the proper dependencies for GCHP.  Tagging @yidant.

**Comment by mgarciavi** [comment]
Thanks so much, Bob!

The point is:

1) For the issue related to gcc 10.2.0 (compilation error) I already was using ESMF older than  ESMF 8.4.2  ( I had above the libraries; you can see in my first message   "(8) esmf-8.0.1-gcc-10.2.0-ou3tiq7";  sorry, it was a bit hidden).  For this, we can try now to install  ESMF 8.4.2 to see if it compiles with it...

2) For the issue related to gcc9.4.0 (compiling, but not running,  problem  related to MAPL_Generic.F90, attached document above) I had  already ESMF 8.4.2.  So for this I don't know if you any suggestion, if you have seen this error before.

Thank you again!

**Comment by yidant** [comment]
Hi @mgarciavi, I don't have the experience compiling with gcc 9.4.0 myself, but I have successfully built GCHP with gcc 10.2.0 and esmf 8.4.2. It might be worth giving that a try. 

Alternatively, you could try [using GCHP containers](https://gchp.readthedocs.io/en/latest/supplement/containers.html), and running them with Singularity or Docker on Slurm, depending on your system setup.

**Comment by yantosca** [comment]
Thanks @yidant and @mgarciavi.  The issue with gcc 9.4.0 and MAPL makes me think that the version of MAPL that is in GCHP right now may not be compatible with gcc 9 anymore.  I know that MAPL skews towards the newer compiler versions, since they need to use some of the newer Fortran standard language features (mostly dealing with object-oriented programming), which may not be present in the older compiler versions.

**Comment by mgarciavi** [comment]
Thanks so much  @yidant  and @yantosca.

At the moment, we have our computing support team  on vacation, so we have to wait until next week to have ESMF 8.4.2 installed with gcc 10.2.0. I will write you when we can try this option.

Meanwhile we have been trying another local cluster (“local cluster 2”, in this comment) and the singularity issue.

So I summarize the situation (although no much progress...  ) :
 
1)	In local cluster 2  we have gcc11.2.0. We’ve tried to compile&run the model here, with the following  libraries:

-  cmake/3.18.2   
-  gcc/11.2.0
- openmpi_gcc11/4.0.4  
- hdf5/1.12.0_gcc-11.2.0  
- netcdf/4.7.4_gcc-11.2.0
- ESMF 8.4.2

Compilation was OK. But, when running, we  have similar problems than those with gcc9 /ESMF8.4.2 in “local cluster 1”.
I’m attaching the log file and gchp_out in ”local cluster 2”, in case you have any clue on how to continue with this

(and forgetting about the  error initializing an OpenFabrics device, cuda issue..)

I've tried 36 and 24 cores (the files attached are with 24c, but they have similar errors with 36c). There are issues with PEs, we're not used to this...and neither with Timers... 

2)	 We don’t have singularity installed in “local cluster 1”; again we have to wait. But we have it in “local cluster 2”.
Until the moment we haven’t succeeded. When executing the script it asks for netcdf libraries, but those are supposed to be in the container, if we well understood... (Probably it will be better to open a new issue on singularity)

Thank you very much again for your support!
[logfile-00000.txt](https://github.com/user-attachments/files/16785308/logfile-00000.txt)
[setCommonRunSettings.txt](https://github.com/user-attachments/files/16785309/setCommonRunSettings.txt)
[gchp_out_24c.txt](https://github.com/user-attachments/files/16785310/gchp_out_24c.txt)

**Comment by lizziel** [comment]
Hi @mgarciavi. It appears the issue is the restart file. The log error is here:
```
 Character Resource Parameter: GCHPchem_INTERNAL_RESTART_FILE:gchp_restart.nc4
 Character Resource Parameter: MAPL_ENABLE_BOOTSTRAP:YES
pe=00023 FAIL at line=06123    MAPL_Generic.F90                         <Factories not equal>
```

This typically happens if you are using a restart file with a grid that does not match your run grid. I will look closely at your log to see if I spot any configuration problems. Could you also check your restart file to make sure you can open it and it is indeed c24?

**Comment by mgarciavi** [comment]
Thanks so much @lizziel !

Yes, the restart issue is something we had in mind since the begginning, although we had closed that doubt, once we saw the files correctly with ncview and ncdump.

But.... Now that you also suspect that the restart files could be the problem, we came back today to that issue (also because as we are now using the other cluster ("local cluster 2"), maybe we had something wrong with those files that we hadn't checked.).

So, although we could again see the files OK with ncview (by the way, those files are a bit strange to us.. not global maps, as for gccclassic? As we are new gchp users, this is not very clear to us ..), we decided to download them again, but directly in the website. Our previous download had been done with the bashdatacatalog tool.

So, what we realised is that, strangely, the files do not seem to have the same content, as if they were exchanged.. This is the relation we found (if I'm not wrong):

-  Bashcat 30c  = Website 24c
-  Bashcat 48c = Website 30c
-  Bashcat 98c = Website 48c
-  Bashcat 24c = Website 30c
 
So I did a new link for the restart 24c file to the one directly downloaded and things changed, that part was OK. We have now another issue, but I will look at it tomorrow (a file missing, GEOS-Chem ERROR [0011]: LINOZ (LINOZ_READ): REQUIRED FILE NOT FOUND ./ChemDir/Linoz_200910/Linoz_March2007.dat, so I will check that tomorrow). But we are happy with the progress,  thank you very much for you help.

So  could there be something with the bashcatalog tool? (or could we have done something wrong? I can't guess now in which step that could have happened..). And this happened twice, as we had to download the exdata directory to our "local cluster 1" and "local cluster 2"... Both restart datasets had the same problem..

I'm attaching the new gchp-log.txt anyway for you to see the change.

(And also I will try with our old failed trials with gcc9 in our "local cluster 1")

Thanks again!

[gchp_out_24c-new.txt](https://github.com/user-attachments/files/16802950/gchp_out_24c-new.txt)

**Comment by lizziel** [comment]
Hi @mgarciavi, thanks for following up on what the issue was. There must be a bug in bashdatacatalog involving GCHP restart files. I am pinging @yidant who is a GEOS-Chem Support Team member who uses bashdatacatalog.

**Comment by lizziel** [comment]
I also wonder if this problem is related to https://github.com/geoschem/GCHP/issues/428

**Comment by yantosca** [comment]
Hi @mgarciavi, also see this comment: 

https://github.com/geoschem/GCHP/issues/428#issuecomment-2231954149

I think you might have better luck using wget to download the files than curl.

**Comment by mgarciavi** [comment]
Thanks @lizziel and @yantosca .

1) Yes,  there could be a bug in bashdatacatalog, although it seems that not only for the restart files. I'm attaching a job file of the download process, where you can see that the target file names are not the same as the original files being downloaded (it seems as if the target name is the same as the next one to be downloaded?). 

The downloading order was: 

bashdatacatalog-list -am -r 2019-06-30,2019-08-01 -f xargs-curl MyCatalogs/*.csv MyCatalogs/**/*.csv | xargs curl

So, if you see the exdata-download log file, even if the reading of some files didn't make the model fail during execution  (because of a format similar to the expected file) data will be wrong (different dates). We need to download everything again to be sure that we have the correct files.
[slurm-download-exdata.txt](https://github.com/user-attachments/files/16837861/slurm-download-exdata.txt)

2) On the other hand, we have tried to advance more,  only to see if the model works. After many files missing and downloading them directly on the website, we found an error with CLOUD. I'm also attaching the error, in case you have seen this before (CLOUDJ_ERROR [0005]: Error in read --> LOCATION:  -> at RD_CLD in module cldj_init_mod.F90). We haven't had time yet to go deeper on this. Also, we are not sure if this can have any relation with the wrong named files.

[gchp_log.txt](https://github.com/user-attachments/files/16838143/gchp_log.txt)

3) To continue, while solving the previous points and waiting for your advice on them, we put off the cloud option  (  photolysis:     activate: false, in geoschem_config.yml) so FAST_JX is now acting; in this case there is a file missing that we cannot directly download (it's forbidden in the website):   In case you could make it accessible. The file is:

exdata//CHEM_INPUTS/FAST_JX/v2024-05//so4.dat

Thank you so much for all your help and time!
Marta

**Comment by lizziel** [comment]
Hi Marta, these errors look like more problems downloading data, possibly with incorrect name. For the Cloud-J error, the problem is in subroutine RD_CLD. You can find where that subroutine within the top-level source code using `grep -ir "call RD_CLD" *`. This will recursively (`r`) look through all files (`*`) in the directory for the string regardless of case (`i`). That should lead you to lines of code here: https://github.com/geoschem/Cloud-J/blob/291a1612cb30f09fd56e761bdd27a095ab1d9815/src/Core/cldj_init_mod.F90#L140-L145

```
      ! Read in cloud scattering data
      call RD_CLD(AMIROOT,JXUNIT,TRIM(DATADIR)//'/'//'`FJX_scat-cld.dat`',rc)
      if ( rc /= CLDJ_SUCCESS ) then
         call CLOUDJ_ERROR('Error in RD_CLD', thisloc, rc)
         return
      endif
```

The file being looked for is hard-coded in the code above as `FJX_scat-cld.dat`. The directory would be the Cloud-J inputs directory in configuration file `geoschem_config.yml`. We should update the error messages to include the filename of the file being opened so it is easier to find that. Check to see if you have that file. If you do have it, using wget to download it from WashU and then compare that file to what you have. I wonder if the one you have is actually a different file with the same name.

Regarding `so4.dat`, I am copying Yidan (@yidant) who is the WashU data manager to check permissions for file `so4.dat`. We have a separate open issue about another file in that folder not being accessible due to permissions (https://github.com/geoschem/geos-chem/issues/2444). 

We will look into what is going wrong with bashdatacatalog. Thank you for providing your log file showing the pattern of incorrect links.

**Comment by mgarciavi** [comment]
Hi @lizziel,

Yes, finally we managed to download everything again with wget. We had to include in the catalogue list, files that were not included but were necessary to run the latest version 14-4-3 (maybe my colleague  @cora579 can say more on this).

The file FJX_scat-cld.dat  was missing in the directory (yes, it would be great to have other messages, saying that the file is not found; we found more files like that, without a "file not found" message, but producing the code fail for that reason)

Now, yes, it seems that the model is running. We will check also the previous compilers, now that we know that the problem was related to the exdata files.

Thanks again!

**Comment by yantosca** [comment]
Thanks @mgarciavi, @cora579, and @lizziel!

**Comment by cora579** [comment]
Hi @lizziel 

With respect to the catalog files that @mgarciavi mentioned, we used the catalogs files located in [http://geoschemdata.wustl.edu/ExtData/DataCatalogs/14.3.0/], however we realized that the following data collections (necessary for running the latest version 14-4-3) were not included in those catalog files:

- In EmissionsInputs.csv file:
HEMCO/GT_Chlorine//v2024-05
HEMCO/NOAA_GMD/v2023-10
HEMCO/VOLCANO/v2024-04

- In ChemistryInputs.csv file:
CHEM_INPUTS/FAST_JX/v2024-05

I hope this could help.

Thanks!

**Comment by yantosca** [comment]
Thanks @cora579.  I'll doublecheck the input-data-catalogs repo.

**Comment by yidant** [comment]
Thanks @mgarciavi for reporting the bashdatacatalog issue! 

We looked into it and found this issue results from the `xargs curl` command. It failed to process the multi-line downloading list generated by bashdatacatalog. It caused mismatching between curl options. To handle multi-line input with xargs, you could use the `-L 1` to specify that only one line of input should be passed to curl at a time. This issue can be fixed by using `xargs -L 1 curl` instead.

**Comment by lizziel** [comment]
I will close out this issue now. Please reopen if this is still a problem.
