### ISSUE TITLE
[BUG/ISSUE] Ifort19+ required for 13.1 release

### ISSUE THREAD

**Issue by lizziel** [geoschem/GCHP#91]
### Description of the problem
Using ifort18 with GCHP 13.1+ may result in an error due to upgrade of `Goddard-Fortran-Ecosystem` libraries. The error is described in detail at https://github.com/GEOS-ESM/MAPL/issues/779. If you encounter it you will see this:
```
forrtl: severe (189): LHS and RHS of an assignment statement have incompatible types
Image              PC                Routine            Line        Source
gchp               0000000002DE89C6  Unknown               Unknown  Unknown
libMAPL.shared.so  00002B04BD5AB957  fy_lexer_mp_pop_t     Unknown  Unknown
libMAPL.shared.so  00002B04BD5A9857  fy_lexer_mp_get_t     Unknown  Unknown
libMAPL.shared.so  00002B04BD574C29  fy_parser_mp_top_     Unknown  Unknown
libMAPL.shared.so  00002B04BD57294E  fy_parser_mp_load     Unknown  Unknown
libMAPL.shared.so  00002B04BD4D8431  pfl_loggermanager     Unknown  Unknown
gchp               00000000018F5C16  mapl_applications         108  ApplicationSupport.F90
gchp               00000000018F5F0C  mapl_applications          39  ApplicationSupport.F90
gchp               0000000000F4D61A  mapl_capmod_mp_ne         106  MAPL_Cap.F90
gchp               000000000053A60C  MAIN__                     29  GCHPctm.F90
gchp               00000000005393DE  Unknown               Unknown  Unknown
libc-2.17.so       00002B04C0651555  __libc_start_main     Unknown  Unknown
gchp               00000000005392E9  Unknown               Unknown  Unknown
```

**Comment by lizziel** [comment]
Given that ifort18 compiler was released more than four years ago (Jan 2017) we will deprecate support for it in GCHP 13.1. If you do not have a more recent Intel compiler then best switch to the GNU fortran compiler. GNU 8.3+ works with GCHP 13.1, although GNU 10 has not yet been tested. Ifort19 also works.
